### ISSUE TITLE
Evaluation for multiple vanishing points

### ISSUE THREAD

**Issue by yanconglin** [zhou13/neurvps#10]
HI, Yichao,

Thanks for the nice work!

Currently I have two concerns regarding the evaluation.
1. Could  you please explain [" if dst < np.pi / n:" ](https://github.com/zhou13/neurvps/blob/236fc24484ae0a704bc411a32a916df448e40897/eval.py#L133)? It is not always the case that two vps are this far (cosine distance) from each other, at least in the toy dataset I created by hand.  Sometimes, the angular distance between two vps is smaller than this threshold. I would assume there are extra constraints on the datasets (camera matrix) used in the paper?

2. Was wondering if Neurvps is possible to detect vps (>3) in non-Manhatten world.

Thanks in advance!

Kind regards,
Yancong

**Comment by zhou13** [comment]
1. Yes. The datasets used in the paper either contain one dominant vanishing point or three orthogonal vanishing points as assumed in the Manhatten world.

2. To detect vanishing points in the non-Manhatten world, the simplest method is probably to change the line you mentioned to another heuristics expression or constant value. A better implementation might combine the minimal consine distance constraints with non-maximal suppression on the vanishing point heat map.

**Comment by yanconglin** [comment]
Thanks for the reply.
Regarding answer 1: Even though in the Manhatten world (3 othorgonal vps),  " if dst < np.pi / n" does not hold all the time. From my observation (on a toy dataset, with randomly generated camera matrix), the cos_distance between two orthogonal vps can be smaller than this PI/3 in some cases. So I was wondering in which case  " if dst < np.pi / n" holds? Guess the intrinsic (extrinsic) matrices have some sort of influence on this threshold. But so far it is not clear to me. Or am I completely wrong?

**Comment by zhou13** [comment]
Each vanishing point corresponds to a set of parallel lines. Therefore, we can represent each VP with its direction vector. The cosine constraints basically say that the angle between two sets of parallel lines (of the VP) should be larger than PI/3.  In the cases say n = 3. np.pi / 3 = 60 degree < 90 degree. Therefore,  "dst < np.pi / n" should hold for the Manhatten world.

I think you may not use the correct camera intrinsics if  "dst < np.pi / n" does not hold in Manhatten settings.

**Comment by zhou13** [comment]
I will close this issue for now. Let me know if you still have any questions.
