### ISSUE TITLE
Predict on Single Image?

### ISSUE THREAD

**Issue by m-aliabbas** [zhou13/neurvps#15]
Is there any way to predict the results on a single image and plotting the vanishing points on it.

**Comment by m-aliabbas** [comment]
In other words I just need help in how can I plot predicted VP

**Comment by zhou13** [comment]
Read the FAQ.

**Comment by m-aliabbas** [comment]
Sorry for distrurbing. I have read the FAQ I found two function to_pixel and to_label. But I looked at code. I did not find the defination of them. Can you point me how to import them.

**Comment by zhou13** [comment]
How about the first entry of the FAQ?

**Comment by zhou13** [comment]
I will close your issue as I think the first entry of the FAQ answers the exact same question.
