### ISSUE TITLE
about Size mismatch error

### ISSUE THREAD

**Issue by YouJoong** [zhou13/neurvps#18]
I am trying to test my data set with the tmm17 pre-trained model. 
So, I downloaded the tmm17 pre-training model from the google driver and tried the following.
However, the following error message occurred:
 python eval.py -d 0 logs/NHS/config.yaml logs/NHS/checkpoint_best.pth.tar
{   'io': {   'augmentation_level': 2,
              'datadir': 'data/NHS/',
              'dataset': 'TMM17',
              'focal_length': 2.7,
              'logdir': 'logs/',
              'num_vpts': 1,
              'num_workers': 4,
              'resume_from': 'logs/200107-013044-14545f5-tmm17-bugfix-lr1e-4-long',
              'tensorboard_port': 0,
              'validation_debug': 0,
              'validation_interval': 8000},
    'model': {   'backbone': 'stacked_hourglass',
                 'batch_size': 8,
                 'conic_6x': False,
                 'depth': 4,
                 'fc_channel': 1024,
                 'im2col_step': 32,
                 'multires': <BoxList: [0.0051941870036646, 0.02004838034795, 0.0774278195486317, 0.299564810864565]>,
                 'num_blocks': 1,
                 'num_stacks': 1,
                 'output_stride': 4,
                 'smp_multiplier': 2,
                 'smp_neg': 1,
                 'smp_pos': 1,
                 'smp_rnd': 3,
                 'upsample_scale': 1},
    'optim': {   'amsgrad': True,
                 'lr': 0.0001,
                 'lr_decay_epoch': 60,
                 'max_epoch': 100,
                 'name': 'Adam',
                 'weight_decay': 0.0006}}
Let's use 1 GPU(s)!
Traceback (most recent call last):
  File "eval.py", line 187, in <module>
    main()
  File "eval.py", line 93, in main
    model.load_state_dict(checkpoint["model_state_dict"])
  File "/home/gonghoon/anaconda3/envs/neurvps/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Unexpected key(s) in state_dict: "module.anet.bn00.weight", "module.anet.bn00.bias", "module.anet.bn00.running_mean", "module.anet.bn00.running_var", "module.anet.bn00.num_batches_tracked", "module.anet.conv00.deform_conv.weight", "module.anet.conv00.deform_conv.bias", "module.anet.bn0.weight", "module.anet.bn0.bias", "module.anet.bn0.running_mean", "module.anet.bn0.running_var", "module.anet.bn0.num_batches_tracked", "module.anet.conv0.deform_conv.weight", "module.anet.conv0.deform_conv.bias".
        size mismatch for module.anet.fc3.weight: copying a param with shape torch.Size([5, 1024]) from checkpoint, the shape in current model is torch.Size([4, 1024]).
        size mismatch for module.anet.fc3.bias: copying a param with shape torch.Size([5]) from checkpoint, the shape in current model is torch.Size([4]).

Please let me know how I can solve this problem.
Sorry for being annoying.

**Comment by zhou13** [comment]
I think you image size is incorrect.
