### ISSUE TITLE
offset calculation in ConicConv

### ISSUE THREAD

**Issue by gukai330** [zhou13/neurvps#23]
thank you for your inspiring work!

I have one question regarding the offset calculation in the conic convolution module

https://github.com/zhou13/neurvps/blob/4eec4ecd98eb7e5dddb82d1c4141d63087c74cf1/neurvps/models/conic.py#L44-L48

As I understand it, the offset tensor saves a matrix of pixel offsets of rotated convolutional kernels (pointing to the VP)

\
I think this line already did the job
https://github.com/zhou13/neurvps/blob/4eec4ecd98eb7e5dddb82d1c4141d63087c74cf1/neurvps/models/conic.py#L46
\
what do these lines do?
https://github.com/zhou13/neurvps/blob/4eec4ecd98eb7e5dddb82d1c4141d63087c74cf1/neurvps/models/conic.py#L47-L48

I tried to visualize the kernels with offset with/ without 47~48 lines. 

w/ (this add some weird rotation to the kernel, and the size become different)
![w](https://user-images.githubusercontent.com/85403739/176713396-baac69e4-a080-4c6b-a13c-a75ffc4d84a6.png)
w/o
![wo](https://user-images.githubusercontent.com/85403739/176713503-6b4d5429-5984-471b-9777-492216c90369.png)

does this have anything to do with the CUDA part here?
https://github.com/zhou13/neurvps/blob/4eec4ecd98eb7e5dddb82d1c4141d63087c74cf1/neurvps/models/cpp/deform_im2col_cuda.cuh#L173-L174
also, the dilation here is a bit weird.

thank you again in advance!

**Comment by zhou13** [comment]
If I recall correctly, this is related to the default offset from deformable conv. You need to "offset" the default offset.
