### ISSUE TITLE
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by 0525stone** [zhou13/neurvps#25]
Hi.
I am not familiar with deep learning code.

I am trying to run eval.py on my computer(Windows). I got the error.
after finding out that I can use ubuntu over the windows by using wsl2.
still getting same issues...

how can I solve this matter?
thank you.

**Comment by zhou13** [comment]
Windows are not supported.

**Comment by abish123456** [comment]
Can you provide the solution for this please

**Comment by zhou13** [comment]
I updated the instruction a little bit to provide a bit more information. Hope it helps.
