### ISSUE TITLE
Why modify im2col + GEMM?

### ISSUE THREAD

**Issue by djr2015** [zhou13/neurvps#4]
In the paper you specify you modify im2col + GEMM to implement the conic convolution. 

Given the conic convolution is distinct from standard convolutions only by where the points are sampled from the input, is it not possible just to sample these points in PyTorch, create a 3x3 matrix out of them and apply standard convolutions without needing to modify im2col + GEMM?

I am also currently trying to implement a custom convolution that only differs wrt the standard convolution by where the points are sampled and would prefer to not dig too deep into the backend.

**Comment by zhou13** [comment]
Hi, it is possible to implement conic convolution in pure Python with resampling (basically the same as im2col) and GEMM.  I don't think you need convolution. The main problem is probably it will consume several times more memory than a CUDA implementation.
