### ISSUE TITLE
Help with derivation of line direction as function of vp

### ISSUE THREAD

**Issue by sebamenabar** [zhou13/neurvps#5]
Hi, I have little knowledge in Multiple View Geometry, but have been studying hard these last days. I'm sorry if this is a rookie question, but I've busting my head trying to figure out how you derive eq. 2 from eq. 1. Could clarify that for me please?

Thanks and congratz for the work

**Comment by zhou13** [comment]
You set lambda to infinality so the o term disappear.  You have z \p = \lambda K d. With some linear algebra, you can get the close form for d (eq 2)
