### ISSUE TITLE
Visualization for vanishing point results in 3D and transform to 2D image

### ISSUE THREAD

**Issue by yizhou-wang** [zhou13/neurvps#6]
Thank you for providing this open-source code! I have the following two questions:
1. Are there any visualization tools available to show the vanishing point results? 
2. Moreover, I found the vanishing points are 3D vectors. How can I transform them into 2D image coordinate? 

Thanks!

**Comment by zhou13** [comment]
1. https://github.com/zhou13/neurvps/blob/967be133444fcb1fac3a558a7466d4f2c7853e7b/dataset/su3.py#L45

2. https://github.com/zhou13/neurvps/blob/cdd3f2a53c2dfb75832c549401e354ec58e0b593/neurvps/models/vanishing_net.py#L178
