### ISSUE TITLE
How is the focal length calculated?

### ISSUE THREAD

**Issue by ylxbyy** [zhou13/neurvps#9]
Hello~ There is parameter of focal length in the config file, but it seems that the value is not the true focal length. I noticed a function 'to_pixel(w)', which seems to be used to transform 3D coordinates to 2D pixel coordinates,  in the 'neurvps/neurvps/models/vanishing_net.py' file, and the focal length is used like this 'x = w[0] / w[2] * C.io.focal_length * 256 + 256, y = -w[1] / w[2] * C.io.focal_length * 256 + 256'. Is the focal length here (also in the config file) equal to 1/tan(fov/2)?

**Comment by zhou13** [comment]
See the FAQ.
